/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:9c1bdd97-75ca-46d2-9dd7-83203ec86a8d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_6Vx8dg0OD",
    "aws_user_pools_web_client_id": "nskca2jku91u87p31ug78tk2o",
    "oauth": {},
    "aws_cognito_login_mechanism": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_appsync_graphqlEndpoint": "https://6xc6hgqrtjh25hk3vubhp52lhy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5jjobm6hbjfurhhnm5ntmtltre"
};


export default awsmobile;
